authenticate_user:
  path: /authenticate/user
  controller: App\Controller\UserControllers\AuthenticationController::login
  methods: [ POST ]

user_create:
  path: /user/create
  controller: App\Controller\UserControllers\AuthenticationController::register
  methods: [ POST ]

user_get:
  path: /user/get
  controller: App\Controller\UserControllers\UserController::me
  methods: [ GET ]



