authenticate_user:
  path: /authenticate/user
  controller: App\Controller\UserControllers\AuthenticationController::login
  methods: [ POST ]

user_create:
  path: /user/create
  controller: App\Controller\UserControllers\AuthenticationController::register
  methods: [ POST ]

user_get:
  path: /user/get
  controller: App\Controller\UserControllers\UserController::me
  methods: [ GET ]


refuel_get_all:
  path: /refuel/get
  controller: App\Controller\RefuelControllers\RefuelController::getAll
  methods: [ GET ]

refuel_get:
  path: /refuel/get/{id}
  controller: App\Controller\RefuelControllers\RefuelController::getRefuel
  methods: [ GET ]

refuel_create:
  path: /refuel/create
  controller: App\Controller\RefuelControllers\RefuelController::create
  methods: [ POST ]

refuel_update:
  path: /refuel/update/{id}
  controller: App\Controller\RefuelControllers\RefuelController::update
  methods: [ PUT ]

refuel_delete:
  path: /refuel/delete/{id}
  controller: App\Controller\RefuelControllers\RefuelController::delete
  methods: [ DELETE ]

#  TODO move to dev routes
swagger:
  path: /swagger
  controller: App\Controller\DocumentationControllers\SwaggerController::getSwagger
  methods: [ GET ]
